### ISSUE TITLE
error result while use addDays

### ISSUE THREAD

**Issue by creatxrgithub** [knowledgecode/date-and-time#1]
for(let i=0; i<7; i++) {
    console.log(date.format(date.addDays(fromDate,-7*i),'YYYY-MM-DD'));
}

output:

2017-04-07
2017-03-31
2017-03-24
2017-03-17
2017-03-09  -----------error from here
2017-03-02
2017-02-23

**Comment by knowledgecode** [comment]
Thank you for pointing it out. But I'm not able to reproduce it. Does a country or an area you are living in have summer time?
