### ISSUE TITLE
More explanatory for NaN response

### ISSUE THREAD

**Issue by fulya35** [knowledgecode/date-and-time#11]
Hello,

In the below examples, both of these dates return with NaN, but their reasons are different. Could you please add more clarity for return values?

```
1) date.parse('Jam 1 2017', 'MMM D YYYY');                     // => NaN
2) date.parse('Feb 29 2017', 'MMM D YYYY');                    // => NaN 
```
------------------------------------------------------------------------------------------
1) No such month name
2) Not in the right range for month

**Comment by knowledgecode** [comment]
Returning the messages in the parse() function is difficult since it means a breaking change. We'll consider adding a new function to do it in the future version.

**Comment by knowledgecode** [comment]
Quite a long time has been passed, we finally dealt this issue. As a result, we decided to add a new function, `preparse()`, returns an object of parsing result. Unfortunately the function doesn't return concrete reason for failure, but this object will help you to infer the failure reason. Please see README.md for more details.
