### ISSUE TITLE
Safari problem

### ISSUE THREAD

**Issue by VoroshilovMax** [knowledgecode/date-and-time#12]
I have issue with safari browser! he is give me NaN from JSON Api format liker "2018-04-01 00:00:00".
This package can solve my problem? I did not try to use yet this package.
May be someone had this problem before?

**Comment by knowledgecode** [comment]
Probably, yes. You can convert the date string to a Date object like this.
```JS
let str = '2018-04-01 00:00:00';
let d = date.parse(str, 'YYYY-MM-DD HH:mm:ss');
```
another example
```JS
let str = '2018-04-06T01:11:36.989Z';
let d = date.parse(str, 'YYYY-MM-DDTHH:mm:ss.SSSZ');
```

**Comment by VoroshilovMax** [comment]
Thank you very much, your solution solved my problem!
