### ISSUE TITLE
Escaping of non-date text in a date format

### ISSUE THREAD

**Issue by aprudnikoff** [knowledgecode/date-and-time#14]
I have a date in Spanish given in the following format: `26 de junio de 2015`.
I would like to have ability to escape non-date symbols which can be confused with date tokens.
For example, how it's done in moment.js: `D [de] MMMM [de] YYYY`.

**Comment by knowledgecode** [comment]
It has already supported it:
```js
date.format(new Date(), 'D [de] MMMM [de] YYYY');
```

**Comment by aprudnikoff** [comment]
@knowledgecode that's good, but it doesn't work in parse().
`date.locale('es');
console.log(date.parse('12 de junio de 2018', 'D [de] MMMM [de] YYYY'));`

**Comment by knowledgecode** [comment]
Though it's not documented, in that case, for now, you can write using spaces:
```js
date.locale('es');
// Replace the "de" with 2 spaces.
console.log(date.parse('12 de junio de 2018', 'D    MMMM    YYYY'));
```
We may consider your request in the future version.

**Comment by knowledgecode** [comment]
Quite a long time has been passed, we finally dealt this issue. The `parse()` has supported a `[]` token for escaping characters.
