### ISSUE TITLE
Suggestion: Support AM/PM output with AA format

### ISSUE THREAD

**Issue by bigman73** [knowledgecode/date-and-time#15]
The current version supports output of a.m. or p.m. when using the A format token

The suggestion is to support output of AM or PM when using a new format token: AA

**Comment by bigman73** [comment]
I extended the current module like so, with a 'P' token:
dateAndTime.setLocales('en', {
    P: ['AM', 'PM'],
    formatter: {
        P: function (d/*, formatString*/) { return this.P[d.getHours() > 11 | 0]; }
    }
});

It works but:
1. Why not have this very common logic as part of the core logic?
2. AA cannot work due to the greedy regular expression in the date.format

The regular expression there needs to support AA|A as alternations in that order

**Comment by knowledgecode** [comment]
The `a.m./p.m.` or `AM/PM` are English expressions. So this is a problem specific to English. So we plan to solve it with sort of an extension kit in the future version.

**Comment by knowledgecode** [comment]
Quite a long time has been passed, we have finally introduced a plugin system to this library, and released a plugin of `AA` token you suggested before as one of the official plugins.
