### ISSUE TITLE
Cannot find module './locale/it'

### ISSUE THREAD

**Issue by Mefistophell** [knowledgecode/date-and-time#2]
Hello!
Please, help me. I include `import date from "date-and-time"` within my module which working for frontend (client side). 
Without using `date.locale('it');` that's all working. But when I added `date.locale('it');` there was an error: Cannot find module './locale/it'.

Maybe that don't related with your module, however I hope you can help me.

**Comment by knowledgecode** [comment]
What conversion tools are you using for the browser? Babel and Browserify? Show me the source code if you like.

**Comment by Mefistophell** [comment]
I'm using Gulp and Browserify with the following code: 

```
return browserify({entries: 'components/app.jsx', extensions: ['.jsx'], debug: true})
        .transform('babelify', {presets: ['es2015', 'react', 'stage-1'], plugins: ["syntax-async-functions", "transform-decorators-legacy"]})
        .bundle()
        .pipe(source('bundle.js'))
        .pipe(buffer())
        .pipe(sourcemaps.init({loadMaps: true}))
        .pipe(streamify(uglify()))
        .pipe(sourcemaps.write('./'))
        .pipe(gulp.dest('assets/js'));
});
```

**Comment by knowledgecode** [comment]
Unfortunately, it seems it doesn't fully work with Browserify for now. Rewrite line 285th of it like this as a workaround:
``` js
date.locale = function (code) {
    if (code) {
        lang = code;
    }
    return lang;
};
```
And then, you could write like this:
``` js
import date from './date-and-time';
import it from './locale/it';

date.locale('it');
date.format(new Date(), 'dddd D MMMM'); //=> Mercoledì 3 maggio
```
I plan to take the permanent measure in the near future.

**Comment by Mefistophell** [comment]
Thank You! I'll be using your solution for now. And I'll be following updates.

**Comment by knowledgecode** [comment]
Just released the new version that supports Browserify!
