### ISSUE TITLE
YYYY Year parsing bug

### ISSUE THREAD

**Issue by demigor** [knowledgecode/date-and-time#20]
Hi,

Parsing strings "1/1/1", "1/1/01", "1/1/001" with D/M/YYYY format yields 1 Jan 2001 date. That is correct.

However, parsing string "1/1/0001" with D/M/YYYY format should yield 1 January 1 year, however it yields 1 Jan 2001. 

So effectively, this is not possible to enter close to Christmas dates :)

**Comment by knowledgecode** [comment]
That behavior is a specification. For now, the `parse()` function does not support less than year 100.

OK, we would consider to support it in the future version.

**Comment by knowledgecode** [comment]
Quite a long time has been passed, we finally dealt this issue. The `parse()` has supported less than year 100 AD.
