### ISSUE TITLE
parse() doesn't support timezone offset?

### ISSUE THREAD

**Issue by chellman** [knowledgecode/date-and-time#23]
This returns NaN right now:

`dateAndTime.parse("2019-02-21T07:48:28-0800", "YYYY-MM-DDThh:mm:ssZ");`

I'm working around it using this undocumented behavior, which is good enough for me at this point (the formatter's going to remove all the spaces, but in my code there are enough to make it pass):

`dateAndTime.parse("2019-02-21T07:48:28-0800", "YYYY-MM-DDThh:mm:ss     ");`

But I'm wondering if I've misunderstood something. Is that first line supposed to work?

**Comment by knowledgecode** [comment]
The `parse()` function is not supported token `Z`. So the following code is not working:
```JS
dateAndTime.parse("2019-02-21T07:48:28-0800", "YYYY-MM-DDThh:mm:ssZ");`
```

If you would like to just get a local time from the string, you can write like this:
```JS
// Removing the timezone from both parameters.
dateAndTime.parse("2019-02-21T07:48:28", "YYYY-MM-DDThh:mm:ss");

// Appending exactly the same timezone string to the format string.
dateAndTime.parse("2019-02-21T07:48:28-0800", "YYYY-MM-DDThh:mm:ss-0800");

// Using a wildcard (a blank space). Replace the timezone string (this case is `-0800`) to 5 blank spaces.
dateAndTime.parse("2019-02-21T07:48:28-0800", "YYYY-MM-DDThh:mm:ss     ");
```
