### ISSUE TITLE
Force a 4-digit YYYY

### ISSUE THREAD

**Issue by mathjazz** [knowledgecode/date-and-time#28]
I validate the user input with `date.parse(input, 'DD/MM/YYYY HH:mm')`.

To my surprise, the following inputs are valid:
* `11/11/1 11:11`
* `11/11/12 11:11`
* `11/11/123 11:11`

I would expect only the following one to pass:
* `11/11/1234 11:11`

Is there a format token available to force a 4-digit year?

**Comment by knowledgecode** [comment]
The rule of the current `YYYY` token may have been ambiguous, so we are going to change it at the next version. However we must consider carefully because this is a breaking change. If you need the change immediately, add this code snippet to your code:

```JS
const date = require('date-and-time');

// This code modifies the YYYY token to force a 4-digit.
date.extend({
    parser: {
        YYYY: function (str) {
            return this.exec(/^\d{4}/, str);
        }
    }
});

date.parse('11/11/1 11:11', 'DD/MM/YYYY HH:mm');    // Invalid Date

// You could also use an isValid to validate the string.
date.isValid('11/11/1 11:11', 'DD/MM/YYYY HH:mm');  // false
```

**Comment by knowledgecode** [comment]
Just published a new version which includes this change.

**Comment by mathjazz** [comment]
Thanks, works beautifully!
