### ISSUE TITLE
Parsing & Performance

### ISSUE THREAD

**Issue by ronak2121** [knowledgecode/date-and-time#30]
Hi,

I've noticed that parsing requires quite a bit of computation, with regex's and parsing; based on my own performance benchmarking of my code; I can see the parse call contributes about 35% of my Javascript code's running time.

I was wondering if you could please see what you can do to better do precomputation. For example, for parsing, the string format is usually known upfront; and can be "precomputed" into the data structures you would need; so you can do your translations later.

There may be other ideas, but this is one that comes to mind.

Thanks,

Ronak

**Comment by ronak2121** [comment]
and just to note that I'm using date-and-time in a NodeJS app; not in a browser

**Comment by knowledgecode** [comment]
Do you have the parse function processed many times with the same string format? If so, as you say, it would be efficient if it could cache the regexes processing results and reuse them. I'll take a look.

**Comment by ronak2121** [comment]
I’m actually using your package in an AWS Lambda and by preparing an instance of date-and-time to parse my date strings; I can save a significant amount of time.

**Comment by ronak2121** [comment]
Do you have any ETAs on when you think this could be fixed?

**Comment by knowledgecode** [comment]
We implemented it for the time being.

We are going to include it in the next version, but there are still many things to do, such as I/F design, compatibility, testing, documentation, so we can't say when it can be released. At least it is impossible in a few days. If this "alpha" version is acceptable, copy and run the following code to see the effect. With a simple benchmark, it seems to be about 60% faster. Please let me know if your implementation seems to be faster. :P

```JS
// Load "date-and-time" module.
const date = require('date-and-time');

// This is a compile function. The function name might be change.
date.compile = function (formatString) {
    var re = /([A-Za-z])\1*|./g, keys, pattern = [formatString];

    formatString = formatString.replace(/\[[^\[\]]*]|\[.*\][^\[]*\]/g, function (str) {
        return str.replace(/./g, ' ').slice(2);
    });
    while ((keys = re.exec(formatString))) {
        pattern[pattern.length] = keys[0];
    }
    return pattern;
};

// Rewrite the preparse function.
date.preparse = function (dateString, arg) {
    var parser = locales[lang].parser, token, result, offset = 0,
        pattern = typeof arg === 'string' ? date.compile(arg) : arg, formatString = pattern[0],
        dt = { Y: 1970, M: 1, D: 1, H: 0, A: 0, h: 0, m: 0, s: 0, S: 0, _index: 0, _length: 0, _match: 0 };

    dateString = parser.pre(dateString);
    for (var i = 1, len = pattern.length; i < len; i++) {
        token = pattern[i];
        if (parser[token]) {
            result = parser[token](dateString.slice(offset), formatString);
            if (!result.length) {
                break;
            }
            offset += result.length;
            dt[token.charAt(0)] = result.value;
            dt._match++;
        } else if (token === dateString.charAt(offset) || token === ' ') {
            offset++;
        } else {
            break;
        }
    }
    dt.H = dt.H || parser.h12(dt.h, dt.A);
    dt._index = offset;
    dt._length = dateString.length;
    return dt;
};
```

How To Use
```JS
const pattern = date.compile('MMM. D YYYY h:m:s A');

date.parse('Nov. 6 2019 1:11:11 p.m.', pattern);
date.parse('Nov. 6 2019 2:22:22 p.m.', pattern);
date.parse('Nov. 6 2019 3:33:33 p.m.', pattern);
```

**Comment by knowledgecode** [comment]
Oops!

Sorry, the above code cannot be run. I'm going to push the whole code to the `develop` branch later, please check out from there.

**Comment by ronak2121** [comment]
I tried your changes and hey we’re about 15% faster for me on my laptop. It was almost insignificant in the Lambda.

**Comment by knowledgecode** [comment]
Oh, no. That's too bad. :disappointed:
Although we are not sure why it is almost insignificant in the Lambda, anyway, we are going to release it when it's ready.

**Comment by knowledgecode** [comment]
We are not sure why the precompiling a string doesn't have an effect on AWS lambda. The reasons are because we don't know about AWS lambda well, and we don't know how are you using the module. If it is parsing many date time string per **one call,** for example, code must be like this:

```JS
// dummy lambda function
{
  const pattern = date.compile('MMM. D YYYY h:m:s A');
  const many_results = [];

  for (const dateString of many_date_string) {
    many_results.push(date.parse(dateString, pattern));
  }
  return many_results;
}
```

However, in your case, maybe it is parsing one date time string per one call? If so, the `precompile()` must be call every time. We guess this is the reason why it doesn't have an effect.

It may be wrong.

As a precompiling result is an array of string, serialize (like a JSON) and save it somewhere, and then, every time, deserialize it and call the `parse()`:

```JS
// dummy lambda function
{
    const pattern = date.compile('MMM. D YYYY h:m:s A');

    save_somewhere(JSON.stringify(pattern));  // pseudo code
}
```

```JS
// dummy lambda function
{
    const pattern = JSON.parse(load_from_somewhere(pattern));  // pseudo code

    return date.parse(dateString, pattern);
}
```
