### ISSUE TITLE
export default issue

### ISSUE THREAD

**Issue by fabianmarcus** [knowledgecode/date-and-time#31]
I'm used to import your (nice) lib like this:

`import DateTime from 'date-and-time'`

However, after I've updated to 0.11. I get this warning: 

> export 'default' (imported as 'DateTime') was not found in 'date-and-time'

Did you remove this intentionally or accidentally?

**Comment by knowledgecode** [comment]
No, nothing has changed. You are using something transpiler (babel and so on), aren't you? That error seems the transpiling is failing. I suppose you should rebuild all the modules again.

**Comment by fabianmarcus** [comment]
Yeah, you're right, I also had to update and republish my other modules which use your lib. Now it's working again.
