### ISSUE TITLE
Unable to parse datetime strings with six millisecond digits

### ISSUE THREAD

**Issue by eaardal** [knowledgecode/date-and-time#32]
Hi

I'm having some trouble parsing strings with six millisecond digits using `.parse()`.

The strings look like this: `2019-11-13T10:22:16.866122Z` `2019-11-11T10:23:23.392706Z`

I've tried these formats:
```
"YYYY-MM-DDTHH:mm:ss.SSSSSSZ" (not listed as a supported format)
"YYYY-MM-DDTHH:mm:ss.SSSZ" (listed as a supported format for 3 ms digits)
"YYYY-MM-DDTHH:mm:ss"
```

If the string is shortened to `2019-11-13T10:22:16Z`, the format `YYYY-MM-DDTHH:mm:ssZ` works just fine.

Also, if the string is shortened to just 3 millisecond digits `2019-11-13T10:22:16.866Z`, the format `YYYY-MM-DDTHH:mm:ss.SSSZ` works just fine.

To play with it you can use https://npm.runkit.com/date-and-time
and paste in this:

```
var dateAndTime = require("date-and-time")

var timestamp = "2019-11-13T10:22:16.866122Z";
var res = dateAndTime.parse(timestamp, "YYYY-MM-DDTHH:mm:ss.SSSSSSZ");
console.log(res);
```

**Comment by knowledgecode** [comment]
I have never seen such a 6-digit millisecond number. [Here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/setMilliseconds), MDN says a `millisecondValue` is between 0 and 999.

In millisecond, digits number represent accuracy, not size. So one way to solve this problem is to delete or ignore the last 3 digits:

(1)
```JavaScript
var dateAndTime = require("date-and-time");

var timestamp = "2019-11-13T10:22:16.866122Z";
// It assumes the date string length is fixed.
timestamp = timestamp.substring(0, 23);
var res = dateAndTime.parse(timestamp, "YYYY-MM-DDTHH:mm:ss.SSS");
console.log(res);
```

(2)
```JavaScript
var dateAndTime = require("date-and-time");

var timestamp = "2019-11-13T10:22:16.866122Z";
// White spaces means wild card.
var res = dateAndTime.parse(timestamp, "YYYY-MM-DDTHH:mm:ss.SSS   Z");
console.log(res);
```

**Comment by eaardal** [comment]
I've never seen 6-digit millisecond numbers before either, but this one API we're using use this format exclusively.

I use something like (1) now to work around this issue. Didn't know about the white space trick, pretty neat, although a bit strange unless you have the comment to explain it.
