### ISSUE TITLE
Wrong parsing of compact year notation

### ISSUE THREAD

**Issue by demigor** [knowledgecode/date-and-time#34]
Parsing of "1/1/1" with format "DD/MM/Y" results to 1/1/1901 year, what is difficult to explain to end user.

**Comment by knowledgecode** [comment]
The code you tried is this?

```JavaScript
date.parse('1/1/1', 'DD/MM/Y');
```

In the latest version, this code will return `Invalid Date`. That is, error. Are you using the latest version?

**Comment by demigor** [comment]
No, D/M/Y.

End-users are very surprised, that 1/1/1, 1/1/01, 1/1/19 results to 19XX years, and 1/1/0 or 1/1/00 cannot be parsed at all.

On Dec 19, 2019 14:36, KNOWLEDGECODE <notifications@github.com> wrote:

The code you tried is this?

date.parse('1/1/1', 'DD/MM/Y');

In the latest version, this code will return Invalid Date. That is, error. Are you using the latest version?

**Comment by knowledgecode** [comment]
Could you show reproducible code here?

> and 1/1/0 or 1/1/00 cannot be parsed at all.

It's in the specifications.

**Comment by demigor** [comment]
What pattern should I use to parse as following:

1/1/1 -> 1 January 2001
1/1/0 -> 1 January 2000
1/1/20 -> 1 January 2020
1/1/75 -> 1 January 1975

Current version seems lost this distinctive feature, the only reason we have chosen date-and-time package.

**Comment by knowledgecode** [comment]
I doubt it is parsed `1/1/1` as `1/1/1901`. Cannot reproduce it.

Hm...

Anyway, to get this library to do what you want, you need to override the default behavior of it. For example like this:

```JavaScript
var date = require('date-and-time');

// Override the default behavior of the YY token.
date.extend({
    parser: {
        YY: function (str) {
            var result = this.exec(/^\d{1,2}/, str);
            result.value += result.value < 70 ? 2000 : result.value < 100 ? 1900 : 0;
            return result;
        }
    }
})

// Use the YY token instead of the Y.
date.parse('1/1/1', 'D/M/YY');  // => 1/1/2001
date.parse('1/1/0', 'D/M/YY');  // => 1/1/2000
date.parse('1/1/20', 'D/M/YY'); // => 1/1/2020
date.parse('1/1/75', 'D/M/YY'); // => 1/1/1975
```

**Comment by demigor** [comment]
So we have to downgrade to 0.6.3 version, which successfully parses 1/1/1, 1/1/0, etc.

Usually package breaking changes do not introduce degradation in functions, what is not the case here.
