### ISSUE TITLE
Invalid Date error trying to parse a string containing AM or PM 

### ISSUE THREAD

**Issue by aliemami** [knowledgecode/date-and-time#35]
const date = require('date-and-time');
let d = date.parse('Dec, 25 2019 at 3:51 AM', 'MMM, D YYYY at h:m A');
//same error with following line also
//let d = date.parse('Dec, 25 2019 at 3:51 AM', 'MMM, D YYYY at h:m AA (*)');
console.log(d);

output: 
Invalid Date

**Comment by knowledgecode** [comment]
`A` token recognizes only `a.m.` or `p.m.` by default. So you have to use a plugin when to parse `AM` or `PM`.

```JavaScript
const date = require('date-and-time');
// Load a plugin extending `A` token.
require('date-and-time/plugin/meridiem');
// Apply the plugin to this library.
date.plugin('meridiem');

let d = date.parse('Dec, 25 2019 at 3:51 AM', 'MMM, D YYYY [at] h:m A');
console.log(d);
```

This is a misunderstanding:

```JavaScript
//same error with following line also
//let d = date.parse('Dec, 25 2019 at 3:51 AM', 'MMM, D YYYY at h:m AA (*)');
```

However, the document might be difficult to understand. I'll rewrite it.
