### ISSUE TITLE
Parse ISO 8601 dates

### ISSUE THREAD

**Issue by Vringe** [knowledgecode/date-and-time#36]
Is it possible to parse [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) formatted strings?

Example: `2022-05-04T00:00:00.000000Z`

**Comment by knowledgecode** [comment]
Yes, but it seems a bit tricky. That example is too long the millisecond part. And the end of the characters, `Z`, has been reserved word a while ago.

```JS
// Need to append three spaces behind the formatString and enclose Z in parentheses as follows:
date.parse('2022-05-04T00:00:00.000000Z', 'YYYY-MM-DDTHH:mm:ss.SSS   [Z]', true);
```

**Comment by Vringe** [comment]
Yes that worked. Thank you!
