### ISSUE TITLE
More flexibility for AM/PM formats

### ISSUE THREAD

**Issue by filipemir** [knowledgecode/date-and-time#4]
Hello!

I think the regEx for AM/PM in times could use some work as well:

```js
console.log(dateAndTime.parse('11:23 p.m.', 'hh:mm A')) // Thu Jan 01 1970 23:23:00 GMT-0500 (EST)
console.log(dateAndTime.parse('11:23 P.M.', 'hh:mm A'))   // NaN
console.log(dateAndTime.parse('11:23 PM', 'hh:mm A'))   // NaN
console.log(dateAndTime.parse('11:23 pm', 'hh:mm A'))   // NaN
```

I may submit a PR when I have a second, but just wanted to document it in the meantime. Thank you!

**Comment by knowledgecode** [comment]
It is undocumented but you can extend a default parser like this:
```js
var dateAndTime = require('date-and-time');

dateAndTime.setLocales('en', {
    A: ['a.m.', 'p.m.', 'A.M.', 'P.M.', 'am', 'pm', 'AM', 'PM'],
    parser: {
        A: function (str) {
            var finding = this.parser.find(this.A, str);
            finding.index %= 2; // Replace an even number with zero, an odd number with one.
            return finding;
        }
    }
});

console.log(dateAndTime.parse('11:23 p.m.', 'hh:mm A'));
console.log(dateAndTime.parse('11:23 P.M.', 'hh:mm A'));
console.log(dateAndTime.parse('11:23 PM', 'hh:mm A'));
console.log(dateAndTime.parse('11:23 pm', 'hh:mm A'));
```

**Comment by filipemir** [comment]
Cool. That's helpful. But I'm curious what's the argument (if there is one)  for not resolving variants of AM, PM by default?

**Comment by knowledgecode** [comment]
Well, it's for keep the module simple. Although it might be more useful if that were supported by default, I fear that it becomes bloated by taking in various features. I still dither over whether or not to implement it.

**Comment by bigman73** [comment]
I think this feature should be added to the code base

**Comment by knowledgecode** [comment]
Quite a long time has been passed, we finally dealt this issue. We have introduced a plugin system to this library, released the workaround code that we showed before as one of the official plugin.
