### ISSUE TITLE
TypeError: dateObj.getTimezoneOffset is not a function

### ISSUE THREAD

**Issue by JinKun-Yong** [knowledgecode/date-and-time#44]
I tried to run 
`date.format(new Date().toLocaleString("en-US", {
    timeZone: "Asia/Kuala_Lumpur"
}), 'DD-MM-YYYY hh:mma', true);`

However it returns:

 `d = date.addMinutes(dateObj, utc ? dateObj.getTimezoneOffset() : 0),`
                                                       ^

`TypeError: dateObj.getTimezoneOffset is not a function
    at Object.date.format (/Users/JKnet/erider-function-source/node_modules/date-and-time/date-and-time.js:156:56)
    at [stdin]:8:6
    at Script.runInThisContext (vm.js:132:18)
    at Object.runInThisContext (vm.js:309:38)
    at internal/process/execution.js:77:19
    at [stdin]-wrapper:6:22
    at evalScript (internal/process/execution.js:76:60)
    at internal/main/eval_stdin.js:29:5
    at Socket.<anonymous> (internal/process/execution.js:198:5)
    at Socket.emit (events.js:326:22)`

Does it mean I cannot give a timezone aware object?

**Comment by knowledgecode** [comment]
I don't know what return value you expect, but anyway, the 1st parameter of the `format()` should be a Date object. In the above code, it is string.

**Comment by JinKun-Yong** [comment]
I see. It is my mistake, then. My intention is to transform the time from system's UTC to another timezone. So the final value output's the specified timezone's time.

**Comment by knowledgecode** [comment]
This library cannot convert UTC to any timezone, but to **your local timezone**. For example, `29-10-2020 02:42AM` is assumed to be UTC. To create a Date object from this string, write the following:

```js
// Convert the string to a Date object once. In this case, set the 3d parameter to true.
const utc_date = date.parse('29-10-2020 02:42AM', 'DD-MM-YYYY hh:mmA', true);
```

And then,

```js
// Convert the Date object to a string of your local timezone.
const local_string = date.format(utc_date, 'DD-MM-YYYY hh:mmA');
```

If you want to convert the Date object to a string of any other timezone, this library can't answer it.

**Comment by knowledgecode** [comment]
I'll close this. Post again here if you need to more info.

**Comment by JinKun-Yong** [comment]
Okay! Thank you for your help!
