### ISSUE TITLE
All upper case long Month name

### ISSUE THREAD

**Issue by codegenic-works** [knowledgecode/date-and-time#45]
This may be more of a question, but is there a way to parse the following?:

`DECEMBER 10TH 2020`

I tried `MMMM D[TH] YYYY` but I would get Invalid Date.

If I transformed the input string to `December 10TH 2020` it would successfully parse the date.

Any guidance would be greatly appreciated!

If this currently is not supported, I would also think the variations that would be great to support would be any casing of:

1. Month name (long and short)
2. Day of week (long, short, and very short)

Thanks again and great work!

**Comment by codegenic-works** [comment]
I just found: https://github.com/knowledgecode/date-and-time/issues/29. If you consider this issue a duplicate of that one please let me know.

**Comment by knowledgecode** [comment]
Probably yes. Although I'm going to close this issue, feel free to post here again If you find any problems.
