### ISSUE TITLE
Format(tz) fails when timezone string is greater than +1200 (i.e +1300)

### ISSUE THREAD

**Issue by CapnRedB** [knowledgecode/date-and-time#55]
When providing a time string of 2022-02-22T14:00:00.000+1200 and a time format of YYYY-MM-DD[T]HH:mm:ss.SSSZ, formatTZ will succeed.

When providing a time string of 2022-02-22T14:00:00.000+1300 with the same time format, formatTZ will fail with RangeError: Invalid time value.

This might be due to NZDT (New Zealand Daylight Time) being forgotten and the range of "Z" only goes up to 12

**Comment by knowledgecode** [comment]
This is an issue with `parse()` or `parseTZ()`, not with `formatTZ()`, isn't it? By the way, you don't need to use `parseTZ()` if you don't provide any timezone name for the 3rd parameter. Just use `parse()`.  Anyway, I will fix it soon.

**Comment by CapnRedB** [comment]
It might be? I was getting the range error on this line:

`finalTime = date.formatTZ(convertedTimezone,challongeTimeFormat,'America/New_York');`

But the convertedTimezone is the result of:

`let convertedTimezone = date.parse(initialTimeString['time'], challongeTimeFormat,initialTimeString['UTC']);`

So it very well could be.

I workaround it for checking the string for +13:00 beforehand and then just changing it to +12 and subtracting an hour

**Comment by knowledgecode** [comment]
We have fixed the issue and have just released it as v2.1.2. Thank you for pointing this out!
