### ISSUE TITLE
Make it possible to use the library with react typescript

### ISSUE THREAD

**Issue by denis-zhdanov** [knowledgecode/date-and-time#57]
**Problem**

Current instructions suggest doing the following:

1. `npm i date-and-time`
2. `import date from 'date-and-time';`
**Error:** couldn't find a declaration file for module 'date-and-time'

**Comment by knowledgecode** [comment]
Try the following:
```
npm i @types/date-and-time
```

**Comment by knowledgecode** [comment]
TypeScript types are now bundled.
