### ISSUE TITLE
transformTZ doesn't work properly when original time zone is +0000

### ISSUE THREAD

**Issue by CapnRedB** [knowledgecode/date-and-time#58]
transformTZ doesn't handle timezones with UTC.

Steps to reproduce:

```js
const challongeTimeFormat = date.compile('YYYY-MM-DD[T]HH:mm:ss.SSSZ');
const desiredTimeFormat = date.compile('MMM D h:mmA [GMT]Z');


		let initialTimeString = reformatChallongeTime(element.tournament['start_at']);
		let finalTime;
		try {
		finalTime = date.transformTZ(initialTimeString['time'],challongeTimeFormat,desiredTimeFormat,'America/New_York',initialTimeString['UTC']);
		}
		catch (e){
			fs.writeFileSync('G:/Coding Projects/stdout/timeshit.txt','Initial Time String: ' +JSON.stringify(element.tournament['start_at'])+'\nPost Colon Removal: '+JSON.stringify(initialTimeString)+'\nConverted Time Zone: '+JSON.stringify(convertedTimezone)+'\n',{ flag: 'a' });
			throw e;
		}
```
initialTimeString values:
{ time: '2022-03-06T16:00:00.000-0600', UTC: false }
{ time: '2022-03-06T23:00:00.000+0100', UTC: false }
{ time: '2022-03-06T22:00:00.000+0000', UTC: true }

Expected output:
"Mar 6 5:00PM GMT-0500" for all

Actual output:
-0600 and +0100 output: "Mar 6 5:00PM GMT-0500"

+0000 output: "Mar 6 11:00PM GMT-0500"

I remember having to set the UTC to true when I was using parse and format in order to state explicitly that the timezone that was being used was +0000. Don't know why it was necessary but that worked. It seems the transformTZ has the same issue but doesn't take the optional UTC variable. So maybe two birds with one stone here.

**Comment by CapnRedB** [comment]
though looking at the code for transformTZ it's more likely that formatTZ/parseTZ doesn't handle it properly

**Comment by knowledgecode** [comment]
Fixed the bug. This was an issue in `parse()`. Thank you very much for pointing it out.
