### ISSUE TITLE
Consider adding native support for Typescript types

### ISSUE THREAD

**Issue by euberdeveloper** [knowledgecode/date-and-time#59]
Instead of letting a non-synchronized package (@types/date-and-time) do the job, why don't you just add a "types" definition directly to this package?

It would be far better, it is more comfortable for whom uses the types and, generally, very more reliable.

The @types/date-and-time for instance have not been not updated since two years ago and do not support the plugins

![image](https://user-images.githubusercontent.com/33126163/156561900-6f91ae24-3201-448e-b299-6d7689a6c3f3.png)

Even if your code is not Typescript code, it is extremely easy to create the types declaration for javascript code https://www.typescriptlang.org/docs/handbook/declaration-files/dts-from-js.html and could even be automatized with a github action!

**Comment by knowledgecode** [comment]
Thank you for your suggestion. I will consider supporting TypeScript.

**Comment by knowledgecode** [comment]
TypeScript types are now bundled.

**Comment by euberdeveloper** [comment]
Cool
