### ISSUE TITLE
ESM version exposed to environments that don't support ESM (e.g. jest 28)

### ISSUE THREAD

**Issue by simon-paris** [knowledgecode/date-and-time#61]
## Description

The package.json `exports` field declares that the browser will always get the ESM version of the library.

Jest v28 with jsdom will honour `exports`, but does not babelize files in node_modules. Therefore it will crash if you import this library.

```
  "exports": {
    ".": {
      "browser": "./esm/date-and-time.es.js",
      "import": "./esm/date-and-time.mjs",
      "require": "./date-and-time.js"
    },
  }
```

## How to reproduce

Run this script:
```
# install jest and uuid
yarn add jest jest-environment-jsdom date-and-time

# create test scenario
cat << TESTFILE > ./tests.spec.js
test("should import date-and-time without crashing", () => require("date-and-time"));
TESTFILE

yarn jest --env jsdom
```

## Expected behavior

non-nodejs CJS code that imports uuid should receive the CJS version of the library.

**Comment by knowledgecode** [comment]
I'll take a look. Please give me some time.

**Comment by simon-paris** [comment]
Thanks!
