### ISSUE TITLE
Can we substract year?

### ISSUE THREAD

**Issue by phamquankun** [knowledgecode/date-and-time#63]
In your example about substract date, it's just return days or hours or seconds, but not year
![image](https://user-images.githubusercontent.com/67066788/175241712-8d83815b-a84c-420d-9710-6fc5594e6353.png)
Can we substract date and return year?

**Comment by knowledgecode** [comment]
It is difficult for us to calculate the number of years from the result of `subtract`. This is because the number of days in a year is not constant. This is also true for the number of days in a month. If you only need to know the approximate value, you can do the following:

```JS
const a = new Date(2022, 0 , 1);        // 2022-01-01
const b = new Date(2020, 0 , 1);        // 2020-01-01

date.subtract(a, b).toDays() / 365;     // 2.0027397... => approximate 2 years
```
