### ISSUE TITLE
Invalid `Podfile` file: 767: unexpected token at 'Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './package.json' is not defined by "exports" in /…/node_modules/date-and-time/package.json

### ISSUE THREAD

**Issue by jainmca21** [knowledgecode/date-and-time#64]
I have updated the RN version 0.69.1. Getting  below error when execute command 'pod install'.

Error:
'Invalid `Podfile` file: 767: unexpected token at 'Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './package.json' is not defined by "exports" in /…/node_modules/date-and-time/package.json'

**Comment by knowledgecode** [comment]
Fixed the `package.json`, but I'm not sure about React Native so that please make sure whether the problem has been fixed or not.
