### ISSUE TITLE
Format formats incorrect month

### ISSUE THREAD

**Issue by DarkVillager** [knowledgecode/date-and-time#69]
code used:
```js
const date = require('date-and-time'),
	now = new Date(2023, 02, 29);
const eNow = date.format(now, 'YYYY-MM-DD'); // normal date
console.log(eNow);
```

log:
```cmd
2023-03-29
```

**Comment by knowledgecode** [comment]
That is not a bug.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/Date
> `monthIndex`
> 
>     Integer value representing the month, beginning with `0` for January to `11` for December.
