### ISSUE TITLE
isValid does not work correctly

### ISSUE THREAD

**Issue by H03in** [knowledgecode/date-and-time#7]
is valid method does not detect all invalid dates like '-015/11/22'

**Comment by knowledgecode** [comment]
The isValid() method takes two arguments. What do you specify the second argument?

**Comment by H03in** [comment]
yyyy-MM-dd

**Comment by knowledgecode** [comment]
Thanks. I'll take a look.

**Comment by H03in** [comment]
your welcome
i changed that to upercase and was fixed.
