### ISSUE TITLE
addMonth to 2022-03-01 does not add full month

### ISSUE THREAD

**Issue by dondracek** [knowledgecode/date-and-time#70]
consider following code:
```js
const date_and_time = require('date-and-time')
const d = new Date(Date.UTC(2022,2,1)) // 1st of March
const nextMonth = date_and_time.addMonths(d, 1) // nextMonth should be 1st of April
console.log(nextMonth)
```

yields
`2022-03-31T23:00:00.000Z`

tested on Node v18, MacOS, German locale.

**Comment by knowledgecode** [comment]
Thank you for your report. It turned out to be a bug caused by daylight savings time starting on March 26th in Berlin. Wait a few days while we fix it.

**Comment by knowledgecode** [comment]
This issue has been fixed. The new version is v2.4.3. Please check if possible.

**Comment by knowledgecode** [comment]
I've added a `utc` option to the `addMonth()` to clearly whether local time ot utc time should be calculated. In the above case, please rewrite as follows:
```JS
const nextMonth = date_and_time.addMonths(d, 1, true)   // nextMonth should be 1st of April
```
