### ISSUE TITLE
addDays when crossing over from summer to standard time the UTC is incorrect

### ISSUE THREAD

**Issue by Liekele** [knowledgecode/date-and-time#72]
start: Mon Mar 27 2023 00:00:00 GMT+0200 (Central European Summer Time)
end: Mon Apr 10 2023 00:00:00 GMT+0200 (Central European Summer Time)

```
import date from 'date-and-time';
date.addDays(start, -7);
date.addDays(end, -7);
```

### Result:
start: **Sun Mar 19 2023 23:00:00** GMT+0100 (Central European Standard Time)
end: Mon Apr 03 2023 00:00:00 GMT+0200 (Central European Summer Time)

### Expected:
start: **Mon Mar 20 2023 00:00:00** GMT+0100 (Central European Standard Time)
end: Mon Apr 03 2023 00:00:00 GMT+0200 (Central European Summer Time)

### Version:
2.4.3

**Comment by knowledgecode** [comment]
I think your point is correct, but some may disagree. The problem is that `addDays()` and `addMonths()` are ambiguous as to whether the time should be treated as UTC time or local time. So it seems better to add a third argument to these functions to let them specify which time we want to get.

**Comment by knowledgecode** [comment]
I've added a `utc` option to the `addDays()` to clearly whether local time ot utc time should be calculated. In the above case, add `false` to the 3rd parameter. However, the default for this paramter is `false`, so you can leave it as is.
```JS
date.addDays(start, -7, false);
date.addDays(end, -7, false);
```
