### ISSUE TITLE
Module has no default export after upgrade to angular v15

### ISSUE THREAD

**Issue by barryrlmurphy** [knowledgecode/date-and-time#73]
Hi 
I upgraded to angular v15 and as part of v15 angular now changes from commonJS export and import syntax to ECMAScript systax. I now get a bunch of import errors for the 'date-and-time' package because it has no default export and uses the old systax for import (stated in the docs):
`import date from 'date-and-time';`

angular (or any app using ecmascript syntax) will expect something like this:
`import { date } from 'date-and-time';`

I am using v2.0.0 of the 'date-and-time' package

Please advise.

Thanks

**Comment by knowledgecode** [comment]
I'm not sure about Angular, but perhaps the error is a TypeScript error? Try the following to see if the error goes away:
```JS
import * as date from 'date-and-time';
```
Alternatively, adding the following option to `tsconfig.json` may resolve the error:
```
allowSyntheticDefaultImports: true
```
https://www.typescriptlang.org/tsconfig#allowSyntheticDefaultImports

**Comment by barryrlmurphy** [comment]
Hi
Thanks for the reply. I have tried the above and I get a compile error:
`Error: export 'format' (imported as 'date') was not found in 'date-and-time' (possible exports: default)`
This happens after I try to use the 'format' method in date-and-time example:
`return date.format(newDate, fm);`

I have also tried using the following format, but also get compile errors:
`import { default as date } from "date-and-time";`

**Comment by barryrlmurphy** [comment]
I found a fix for the issue in a previously closed issue [(here)](https://github.com/knowledgecode/date-and-time/issues/57)
`npm i --save-dev @types/date-and-time`

Thanks for your help.
