### ISSUE TITLE
addMonts function calculates wrong date for some cases

### ISSUE THREAD

**Issue by esurat20** [knowledgecode/date-and-time#76]
Hello.
Please consider such case:
```
someDate = new Date(Date.UTC(2023,4,31)) // 2023-05-31
my locale: Wed May 31 2023 03:00:00 GMT+0300 (Eastern European Summer Time)

then I am running

date.addMonths(someDate, 1)

and getting

Sat Jul 01 2023 03:00:00 GMT+0300 (Eastern European Summer Time)
```
I am  expecting to get
`2023-06-30` 

For example here when I am adding 1 month to May 31 I have such result `2023-06-30`, see link
https://www.timeanddate.com/date/dateadded.html?d1=31&m1=5&y1=2023&type=add&ay=&am=1&aw=&ad=&rec=

and I have the same result If I am adding 1 month to May 30, see link
https://www.timeanddate.com/date/dateadded.html?d1=30&m1=5&y1=2023&type=add&ay=&am=1&aw=&ad=&rec=

**Comment by knowledgecode** [comment]
I see. The result of adding months at the end of the month is not what you expected. The difference is more pronounced in this example.

```JS
someDate = new Date(Date.UTC(2023,0,31)) // 2023-01-31

date.addMonths(someDate, 1) // 2023-03-04

// Probably you are expecting to get 2023-02-28
```
I'll think about what to do.

**Comment by knowledgecode** [comment]
I've fixed this issue. Thank you for your report.
