### ISSUE TITLE
Miising format 

### ISSUE THREAD

**Issue by ECEAthipanbose** [knowledgecode/date-and-time#83]
how to convert this time format 
YYYY-MM-ddTHH:mm:ss.SSSSSSZZ

ddTHH?
2014-09-14T14:02:45.0174665+01:00

**Comment by knowledgecode** [comment]
Alphabetic characters other than tokens must be bracketed. Specifically, it should be written as follows:
```
YYYY-MM-DD[T]HH:mm:ss.SSSSSSZZ
```
Note that a plugin must be installed to handle milliseconds longer than 4 digits. Even so, it is not possible to have more than 7 digits.
