### ISSUE TITLE
How to format a named offset? (ex: EST)

### ISSUE THREAD

**Issue by alex996** [knowledgecode/date-and-time#86]
Many libraries include a formatting token for named offsets. Ex: in `dayjs`, `z` for EST, `zzz` for Eastern Standard Time, etc. It looks like `Intl.DateTimeFormat` includes [`timeZoneName`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat/DateTimeFormat#timezonename) which could be used for this.

Is there complexity to this feature? Could this be offered with a plugin, if not part of the core? Thank you.

**Comment by knowledgecode** [comment]
Thank you for your input. I will consider it.

**Comment by knowledgecode** [comment]
Added `zz` (time zone name) and `z` (time zone name abbreviation) tokens to the `timezone` plugin. Try it when you have time.
