### ISSUE TITLE
date.parse('15/10/2017', 'DD/MM/YYYY') = NaN

### ISSUE THREAD

**Issue by wasenbr** [knowledgecode/date-and-time#9]
Why date.parse('15/10/2017', 'DD/MM/YYYY') = NaN  ?

**Comment by knowledgecode** [comment]
Really? That code will succeed. Please make sure again.

**Comment by wasenbr** [comment]
This is my test:

const date = require('date-and-time');
console.log(date.parse('15/10/2017', 'DD/MM/YYYY'));

//it show NaN

Node.js v6.10.3   Windows 10
"_npmVersion": "5.0.4"
"version": "0.5.0"

**Comment by wasenbr** [comment]
Yes, it has. This date is the day of change. But not happen on another change days.

**Comment by knowledgecode** [comment]
Fixed it. Could you test the latest version?

**Comment by wasenbr** [comment]
I did run the same test and it works. Great job!

Thanks!
