### ISSUE TITLE
undefined when using typescript

### ISSUE THREAD

**Issue by fhuonder** [knowledgecode/date-and-time#93]
Hi,

I am not sure what the source of my problem is... Maybe you can help me out.

My setup is typescript and I am using webpack.

When having this code (as taken from the readme):
```
import date from 'date-and-time';
import timezone from 'date-and-time/plugin/timezone'

date.plugin(timezone);
```
I get an undefined error for "date" on line 4.

When modifying the code to
```
import * as date from 'date-and-time';
import timezone from 'date-and-time/plugin/timezone'

date.plugin(timezone);

date.formatTZ(d, format, "Europe/Zurich")
```
I get the error that the `formatTZ` function is undefined.

Using `import * as timezone from 'date-and-time/plugin/timezone'` does not work because the call of the `plugin` function yields: No overload matches this call.

Any hints on how to get that running?

Regards,
Florian

**Comment by knowledgecode** [comment]
Please check if the following settings are configured in your `tsconfig.json`. The cause of the error is likely due to one or both of these settings being missing.
```JSON
{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true
  }
}
```

**Comment by fhuonder** [comment]
Hi

Thanks for your response...
`esModuleInterop` was missing.
